/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectodesupermercado.Vista.paneles;



import java.sql.Timestamp;
import java.time.Instant;
import static proyectodesupermercado.Vista.TableUtils.getSelectedIndex;
import proyectodesupermercado.controller.dao.mysql.SolicitudesMySQLDAO;
import proyectodesupermercado.lib.databaseUtils.DatabaseEnvironment;
import proyectodesupermercado.lib.swingadditions.PlaceholderTextField;
import proyectodesupermercado.lib.tableModel.ObjectTableModel;
import proyectodesupermercado.modelo.SolicitudCompra;
import proyectodesupermercado.modelo.SolicitudCompraProducto;

/**
 *
 * @author darkw
 */
public class AceptarSolicitud extends javax.swing.JPanel {
    
private final ObjectTableModel<SolicitudCompraProducto> SolicitudProducto;
private final ObjectTableModel<SolicitudCompra> Aceptados;
    DatabaseEnvironment dbEnv = new DatabaseEnvironment(
                "jdbc:mysql://localhost:3306/ProyectoFinal",
                "root",
                "darkwister171531"
        );
private final SolicitudesMySQLDAO SDAO = new SolicitudesMySQLDAO(dbEnv);
    /**
     * Creates new form ASolicitud
     * @param SolicitudProducto
     * @param Aceptados
     */
    public AceptarSolicitud(ObjectTableModel<SolicitudCompraProducto> SolicitudProducto,ObjectTableModel<SolicitudCompra> Aceptados) {
        initComponents();
        this.Aceptados = Aceptados;
        this.SolicitudProducto = SolicitudProducto;
        SolicitudesAceptadas.setModel(Aceptados);
        SolicitudesPendientes.setModel(SolicitudProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaTextField = new PlaceholderTextField().setPlaceholder("Busqueda");
        busquedaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SolicitudesAceptadas = new javax.swing.JTable();
        BotonAceptarSolicitudes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SolicitudesPendientes = new javax.swing.JTable();
        LabelAceptados = new java.awt.Label();

        busquedaTextField.setColumns(9);
        busquedaTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        busquedaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaTextFieldActionPerformed(evt);
            }
        });

        busquedaButton.setText("Buscar");
        busquedaButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, null, java.awt.Color.gray));
        busquedaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaButtonActionPerformed(evt);
            }
        });

        SolicitudesAceptadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Producto", "Cantidad en Inventario"
            }
        ));
        jScrollPane1.setViewportView(SolicitudesAceptadas);

        BotonAceptarSolicitudes.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        BotonAceptarSolicitudes.setText("Aceptar Solicitudes");
        BotonAceptarSolicitudes.setToolTipText("");
        BotonAceptarSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarSolicitudesActionPerformed(evt);
            }
        });

        SolicitudesPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Producto", "Unidades", "Precio por Unidad"
            }
        ));
        SolicitudesPendientes.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(SolicitudesPendientes);

        LabelAceptados.setBackground(new java.awt.Color(40, 40, 40));
        LabelAceptados.setEnabled(false);
        LabelAceptados.setForeground(new java.awt.Color(221, 221, 221));
        LabelAceptados.setName("LabelAceptar"); // NOI18N
        LabelAceptados.setText("Productos a Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(busquedaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonAceptarSolicitudes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(busquedaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(LabelAceptados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busquedaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(BotonAceptarSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelAceptados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaTextFieldActionPerformed

    private void busquedaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_busquedaButtonActionPerformed

    private void BotonAceptarSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarSolicitudesActionPerformed
        // TODO add your handling code here:
        int i;
        i = getSelectedIndex(SolicitudesPendientes, "Debes seleccionar almenos una entrada de los pendientes");
        if(i == -1){
            return;
        }
        SolicitudCompraProducto solicitud = SolicitudProducto.getRow(i);
        SolicitudCompra aceptado = new SolicitudCompra(solicitud.getIdProductoRegistro(),Timestamp.from(Instant.now()),true);
        Aceptados.addRow(aceptado);
        SolicitudProducto.removeRow(i);

        SDAO.update(aceptado.getId(), aceptado);
    }//GEN-LAST:event_BotonAceptarSolicitudesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptarSolicitudes;
    private java.awt.Label LabelAceptados;
    private javax.swing.JTable SolicitudesAceptadas;
    private javax.swing.JTable SolicitudesPendientes;
    private javax.swing.JButton busquedaButton;
    private javax.swing.JTextField busquedaTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
