/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectodesupermercado.Vista.paneles;

import proyectodesupermercado.Vista.TableUtils;
import proyectodesupermercado.Vista.interfaces.ControlInventario;
import proyectodesupermercado.lib.tableModel.ObjectTableModel;
import proyectodesupermercado.modelo.InventarioProducto;

import javax.swing.JOptionPane;
import java.util.Optional;

/**
 * @author IA
 */
public class Manejo_de_inventario extends javax.swing.JPanel {

    private final ControlInventario controlInventario;
    private ObjectTableModel<InventarioProducto> currentModel;
    /**
     * Creates new form Manejo_de_inventario
     */
    public Manejo_de_inventario(ControlInventario controlInventario) {
        initComponents();

        this.controlInventario = controlInventario;
        this.currentModel = controlInventario.refreshInitialModel();
        mainTable.setModel(currentModel);

        mainTable.getSelectionModel().addListSelectionListener(
                evt -> {
                    int index = mainTable.getSelectedRow();
                    if (index == -1) {
                        return;
                    }
                    InventarioProducto row = currentModel.getRow(index);
                    nombreTextfield.setText(row.getNombre());
                    cantidadProductoSpinner.setValue(row.getCantidad());
                });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaTextfield = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        nombreTextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cantidadProductoSpinner = new javax.swing.JSpinner();
        descontinuarButton = new javax.swing.JButton();

        busquedaTextfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        busquedaTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaTextfieldActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, null, java.awt.Color.gray));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String[]{
                        "Nombre producto", "Cantidad"
                }
        ));
        jScrollPane1.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setResizable(false);
            mainTable.getColumnModel().getColumn(1).setResizable(false);
        }

        nombreTextfield.setEnabled(false);

        jLabel1.setText("Cantidad Producto");

        jLabel2.setText("Nombre Producto");

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cantidadProductoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        descontinuarButton.setText("<html>\n<center>Descontinuar<br>Producto</center>\n</html>");
        descontinuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descontinuarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(busquedaTextfield)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombreTextfield)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cantidadProductoSpinner)
                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(descontinuarButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(busquedaTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nombreTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(cantidadProductoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(descontinuarButton)))
                                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doSearch() {
        if (busquedaTextfield.getText().isBlank()) {
            currentModel = controlInventario.refreshInitialModel();
        } else {
            currentModel = controlInventario.search(busquedaTextfield.getText());
        }
        mainTable.setModel(currentModel);
    }

    private void editSelectedProduct() {
        int index = TableUtils.getSelectedIndex(mainTable, "Debe de selecionar un producto");
        if (index == -1) {
            return;
        }
        InventarioProducto producto = currentModel.getRow(index);
//        if (cantidadProductoSpinner.getValue().equals(producto.getCantidad())) {
//            return;
//        }
        if (JOptionPane.NO_OPTION == JOptionPane.showConfirmDialog(this, "¿Quieres editar este producto?", "", JOptionPane.YES_NO_OPTION)) {
            return;
        }
        producto.setCantidad(((int) cantidadProductoSpinner.getValue()));
        currentModel.fireTableRowsUpdated(index, index);
        Optional<String> msg = controlInventario.editProduct(producto);
        if (msg.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Se cambio la cantidad con exito.");
        } else {
            JOptionPane.showMessageDialog(this, msg.get());
        }
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        editSelectedProduct();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        doSearch();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void busquedaTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaTextfieldActionPerformed
        doSearch();
    }//GEN-LAST:event_busquedaTextfieldActionPerformed

    private void descontinuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descontinuarButtonActionPerformed
        int index = TableUtils.getSelectedIndex(mainTable, "Debe de selecionar un producto");
        if (index == -1) {
            return;
        }
        InventarioProducto producto = currentModel.getRow(index);
        controlInventario.descontinuaProducto(producto);
    }//GEN-LAST:event_descontinuarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField busquedaTextfield;
    private javax.swing.JSpinner cantidadProductoSpinner;
    private javax.swing.JButton descontinuarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JTextField nombreTextfield;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
