/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectodesupermercado.Vista.paneles;

import proyectodesupermercado.Vista.interfaces.ControlManejoGanancias;
import proyectodesupermercado.lib.tableModel.ObjectTableModel;
import proyectodesupermercado.modelo.ProductoManejoGanancias;

/**
 *
 * @author DELL
 */
public class PanelManejoGanancias extends javax.swing.JPanel {

    private final ControlManejoGanancias controlManejoGanancias;
    private ObjectTableModel<ProductoManejoGanancias> mainModel;
    /**
     * Creates new form PanelManejoVentas
     */
    public PanelManejoGanancias(ControlManejoGanancias controlManejoGanancias) {
        initComponents();
        this.controlManejoGanancias = controlManejoGanancias;
        tablaInicial();
    }
    
    private void tablaInicial() {
        tablaInicial(controlManejoGanancias.tablaInicial());
    }
    
    public void tablaInicial(ObjectTableModel<ProductoManejoGanancias> model) {
        TablaManejoGanancias.setModel(mainModel = model);
    }
    
        private void busqueda() {
        if (textFieldProducto.getText().isBlank()) {
            mainModel = controlManejoGanancias.tablaInicial();
        } else {
            mainModel = controlManejoGanancias.buscar(textFieldProducto.getText());
//            textFieldProducto.setText("");
        }
        TablaManejoGanancias.setModel(mainModel);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldBuscador1 = new javax.swing.JTextField();
        labelBuscador1 = new javax.swing.JLabel();
        botonBuscar1 = new javax.swing.JButton();
        labelManejodeVentanas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaManejoGanancias = new javax.swing.JTable();
        labelProducto = new javax.swing.JLabel();
        textFieldProducto = new javax.swing.JTextField();
        botonBuscarProducto = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manejo de Ventas");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manejo de Ventas");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        textFieldBuscador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscador1ActionPerformed(evt);
            }
        });
        textFieldBuscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldBuscador1KeyPressed(evt);
            }
        });

        labelBuscador1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelBuscador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscador1.setText("Buscador");
        labelBuscador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        botonBuscar1.setText("Buscar");
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });

        labelManejodeVentanas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelManejodeVentanas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManejodeVentanas.setText("Manejo de Ganacias");
        labelManejodeVentanas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TablaManejoGanancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "<html>Cantidad<br>de Ventas<htrml>", "Ganancias", "Fecha"
            }
        ) {
            final boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaManejoGanancias.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaManejoGanancias);

        labelProducto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProducto.setText("Producto");
        labelProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        textFieldProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldProductoActionPerformed(evt);
            }
        });
        textFieldProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldProductoKeyPressed(evt);
            }
        });

        botonBuscarProducto.setText("Buscar");
        botonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelManejodeVentanas, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManejodeVentanas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldProductoActionPerformed

    private void textFieldProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldProductoKeyPressed

    }//GEN-LAST:event_textFieldProductoKeyPressed

    private void botonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarProductoActionPerformed
        busqueda();
    }//GEN-LAST:event_botonBuscarProductoActionPerformed

    private void textFieldBuscador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscador1ActionPerformed

    private void textFieldBuscador1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldBuscador1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscador1KeyPressed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaManejoGanancias;
    private javax.swing.JButton botonBuscar1;
    private javax.swing.JButton botonBuscarProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscador1;
    private javax.swing.JLabel labelManejodeVentanas;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JTextField textFieldBuscador1;
    private javax.swing.JTextField textFieldProducto;
    // End of variables declaration//GEN-END:variables

}
