/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectodesupermercado.Vista.paneles;

/**
 *
 * @author DELL
 */
public class PanelVentasYCompras extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentasYCompras
     */
    public PanelVentasYCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFIltrador1 = new javax.swing.JLabel();
        labelFIltrador5 = new javax.swing.JLabel();
        textFieldFiltrador2 = new javax.swing.JTextField();
        labelCompras1 = new javax.swing.JLabel();
        labelFIltrador2 = new javax.swing.JLabel();
        labelFIltrador = new javax.swing.JLabel();
        textFieldTotalVentas = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        labelVentas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelTotalVentas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labelCompras = new javax.swing.JLabel();
        textFieldFiltrador = new javax.swing.JTextField();
        labelTotalCompras = new javax.swing.JLabel();
        textFieldTotalCompras = new javax.swing.JTextField();
        labelCompras2 = new javax.swing.JLabel();
        textFieldGananciaNeta = new javax.swing.JTextField();
        textFieldGananciasPerdidas = new javax.swing.JTextField();
        labelFIltrador3 = new javax.swing.JLabel();

        labelFIltrador1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelFIltrador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFIltrador1.setText("Filtrador");
        labelFIltrador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelFIltrador5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelFIltrador5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFIltrador5.setText("Total Ventas");
        labelFIltrador5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelCompras1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelCompras1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompras1.setText("Compras");
        labelCompras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelFIltrador2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelFIltrador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFIltrador2.setText("Filtrador");
        labelFIltrador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelFIltrador.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelFIltrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFIltrador.setText("Gestion de Compras y Ventas");
        labelFIltrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        textFieldTotalVentas.setEditable(false);

        botonBuscar.setText("Buscar");

        labelVentas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVentas.setText("Ventas");
        labelVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Ganancias", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        labelTotalVentas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTotalVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalVentas.setText("Total Ventas");
        labelTotalVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Gasto", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        labelCompras.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompras.setText("Compras");
        labelCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelTotalCompras.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTotalCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalCompras.setText("Total Compras");
        labelTotalCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        textFieldTotalCompras.setEditable(false);

        labelCompras2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelCompras2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompras2.setText("<html>Ganancia<br>         Neta<html>");
        labelCompras2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        labelCompras2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textFieldGananciaNeta.setEditable(false);

        textFieldGananciasPerdidas.setEditable(false);

        labelFIltrador3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelFIltrador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFIltrador3.setText("Filtrador");
        labelFIltrador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFIltrador3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(722, 722, 722))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldFiltrador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelFIltrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldTotalVentas)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(labelTotalVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(labelVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFieldTotalCompras, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelTotalCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelCompras2)
                                                .addComponent(textFieldGananciaNeta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textFieldGananciasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(labelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelFIltrador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(labelFIltrador3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFiltrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVentas)
                            .addComponent(labelCompras))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCompras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldGananciaNeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldGananciasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalVentas)
                    .addComponent(labelTotalCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelCompras;
    private javax.swing.JLabel labelCompras1;
    private javax.swing.JLabel labelCompras2;
    private javax.swing.JLabel labelFIltrador;
    private javax.swing.JLabel labelFIltrador1;
    private javax.swing.JLabel labelFIltrador2;
    private javax.swing.JLabel labelFIltrador3;
    private javax.swing.JLabel labelFIltrador5;
    private javax.swing.JLabel labelTotalCompras;
    private javax.swing.JLabel labelTotalVentas;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JTextField textFieldFiltrador;
    private javax.swing.JTextField textFieldFiltrador2;
    private javax.swing.JTextField textFieldGananciaNeta;
    private javax.swing.JTextField textFieldGananciasPerdidas;
    private javax.swing.JTextField textFieldTotalCompras;
    private javax.swing.JTextField textFieldTotalVentas;
    // End of variables declaration//GEN-END:variables
}
