/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectodesupermercado;

import java.awt.event.WindowEvent;
import java.security.SecureRandom;
import javax.swing.JFrame;
import proyectodesupermercado.Vista.paneles.Gestor_De_Empresas;

public class App {
    public static ThreadLocal<SecureRandom> secureRandom;
    static {
        // init mysql driver
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.err.println("No se pudo cargar 'com.mysql.jdbc.Driver'");
            System.exit(-1);
        }

        // init secureRandom
        secureRandom = ThreadLocal.withInitial(SecureRandom::new);
    }
    public static void main(String[] args) {
        Gestor_De_Empresas consol = new Gestor_De_Empresas();
         JFrame dennis = new JFrame();
         dennis.add(consol);
         dennis.setVisible(true);
         dennis.pack();
         dennis.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
         
         
    }
}
