/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectodesupermercado.Vista;

import proyectodesupermercado.lib.swingadditions.OnDoubleClick;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import java.util.function.Consumer;

/**
 * @author cheerio-pixel
 */
public class ListaPendientes<T> extends javax.swing.JDialog {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<T> pendientesJList;

    /**
     * Creates new form ListaPendientes
     */
    public ListaPendientes(JComponent component, boolean modal, ListModel<T> listModel, ListCellRenderer<T> listRenderer, Consumer<T> doubleClickAction, boolean closeOnDoubleClick) {
        super((JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, component), modal);
        setLocationRelativeTo(component);

        initComponents();
        pendientesJList.setModel(listModel);
        pendientesJList.setCellRenderer(listRenderer);
        pendientesJList.addMouseListener(
                new OnDoubleClick(l -> {
                    if (closeOnDoubleClick) {
                        close();
                    }
                    @SuppressWarnings("unchecked")
                    JList<T> castedList = (JList<T>) l;
                    // Lesgo java and its backwards compatibility shennnigans.
                    doubleClickAction.accept(castedList.getSelectedValue());
                }));
    }

    private void close() {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pendientesJList = new javax.swing.JList<>();
        cerrarButton = new javax.swing.JButton();

        pendientesJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(pendientesJList);

        cerrarButton.setText("Cerrar");
        cerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                        .addComponent(cerrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarButtonActionPerformed
        close();
    }//GEN-LAST:event_cerrarButtonActionPerformed
    // End of variables declaration//GEN-END:variables
}
